// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using shanuMusicPlayerMVC;
using System;

namespace shanuMusicPlayerMVC.Migrations
{
    [DbContext(typeof(MusicDataContext))]
    [Migration("20190213153820_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("shanuMusicPlayerMVC.AlbumMastera", b =>
                {
                    b.Property<int>("AlbumMasteraID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlbumName");

                    b.Property<string>("ImageName");

                    b.HasKey("AlbumMasteraID");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("shanuMusicPlayerMVC.MusicPlayerMastera", b =>
                {
                    b.Property<int>("MusicPlayerMasteraID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlbumName");

                    b.Property<string>("Description");

                    b.Property<string>("MusicFileName");

                    b.Property<string>("SingerName");

                    b.HasKey("MusicPlayerMasteraID");

                    b.ToTable("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
